/* ============================================================================
 * BUILD — produces a self-contained, dependency-free `index.html`.
 *
 * React, Lucide's SVG paths and the compiled Tailwind stylesheet are all
 * inlined, so the served page issues ZERO third-party requests: it boots on a
 * dead cell connection and works fully offline once the service worker primes.
 *
 *   node build.mjs        (or: npm run build)
 * ========================================================================= */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as esbuild from 'esbuild';

const OUT = 'index.html';
const sha256 = (s) => createHash('sha256').update(s, 'utf8').digest('base64');
const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';

/* 1 — bundle the app (JSX -> ES2019, tree-shaken, minified) ---------------- */
const { outputFiles } = await esbuild.build({
  entryPoints: ['src/app.jsx'],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2019'],
  jsx: 'automatic',
  legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"' },
  write: false,
  outfile: 'app.js',
});
const js = outputFiles[0].text;

/* 2 — compile Tailwind against the sources, keeping only used utilities ---- */
const tmp = mkdtempSync(join(tmpdir(), 'tw-'));
const cssPath = join(tmp, 'out.css');
execFileSync(
  process.execPath,
  ['node_modules/tailwindcss/lib/cli.js', '-c', 'tailwind.config.js',
   '-i', 'src/styles.css', '-o', cssPath, '--minify'],
  { stdio: ['ignore', 'ignore', 'inherit'] }
);
const css = readFileSync(cssPath, 'utf8');
rmSync(tmp, { recursive: true, force: true });

/* 2b — the evidence report prints from a same-origin iframe, which inherits
 *      this page's CSP. Its stylesheet therefore needs a hash here too, or the
 *      PDF comes out as unstyled plain text with no error the user can see. */
const { REPORT_STYLES } = await import('./src/report.js');

/* 3 — inline into the shell. Function replacements keep `$&`-style sequences
 *     inside the bundle from being interpreted as replacement patterns. ---- */
const csp = [
  "default-src 'self'",
  `script-src 'sha256-${sha256(js)}'`,
  `style-src 'sha256-${sha256(css)}' 'sha256-${sha256(REPORT_STYLES)}'`,
  "img-src 'self' data:",
  "connect-src 'self'",
  "worker-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  /* frame-ancestors is header-only — a <meta> CSP cannot carry it, and
     browsers log a warning if you try. Nothing here is framable anyway. */
].join('; ');

const html = readFileSync('src/shell.html', 'utf8')
  .replace('/*__CSS__*/', () => css)
  .replace('/*__JS__*/', () => js)
  .replace('<meta name="color-scheme"', () =>
    `<meta http-equiv="Content-Security-Policy" content="${csp}">\n<meta name="color-scheme"`);

writeFileSync(OUT, html);

/* 4 — service worker, versioned by the exact bytes it caches --------------- */
const version = sha256(html).replace(/[^a-zA-Z0-9]/g, '').slice(0, 12);
writeFileSync(
  'sw.js',
  `/* GENERATED by build.mjs — do not edit. Cache name tracks the shell hash,
   so a rebuilt console evicts the previous one on first load. */
const CACHE = 'turnover-${version}';
const SHELL = ['./', './index.html', './manifest.webmanifest',
  './icon-192.png', './icon-512.png', './icon-maskable-512.png', './icon-180.png'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Network-first so a redeployed console is picked up as soon as there is
   signal; cache-first fallback keeps the app alive when there is none. */
self.addEventListener('fetch', (e) => {
  const { request } = e;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  e.respondWith(
    fetch(request)
      .then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy)).catch(() => {});
        return res;
      })
      .catch(() => caches.match(request).then((hit) => hit || caches.match('./index.html')))
  );
});
`
);

/* 5 — manifest ------------------------------------------------------------- */
writeFileSync(
  'manifest.webmanifest',
  JSON.stringify(
    {
      name: 'Property Turnover Matrix',
      short_name: 'Turnover',
      description:
        'Industrial field console for auditing rental-property inventory across multiple units.',
      start_url: './',
      scope: './',
      display: 'standalone',
      orientation: 'portrait',
      background_color: '#020617',
      theme_color: '#0f172a',
      icons: [
        { src: './icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: './icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: './icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    null,
    2
  ) + '\n'
);

console.log(`  js   ${kb(js)}\n  css  ${kb(css)}\n  html ${kb(html)}  ->  ${OUT}\n  sw   turnover-${version}`);
