/* GENERATED by tools/set-passcode.mjs — do not edit by hand.
 *
 * An empty `hash` disables the gate. The plaintext passcode is not stored
 * here or anywhere else in the repository.
 *
 * This is a soft gate on a public static page: see the warning at the top of
 * src/passcode.js before relying on it for anything.
 */
export const PASSCODE = {
  salt: "999467a61beff38909014ad84c049b1d",
  iterations: 20000,
  hash: "79935824e44b1fdbbbc2abb367f34e51ac240ce5072dd11312ce688cc91e018f",
};
